server.port=${PORT}
thirdeye.uniqueCode=${UNIQUE_CODE}
eureka.client.service-url.defaultZone=${THIRDEYE_RESUME_UPDATER_SERVER_URL}
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}
eureka.instance.prefer-ip-address=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443
eureka.instance.non-secure-port-enabled=true